### PR TITLE
fix: animation when resizing SegmentedButton (#312)

### LINKED ISSUE #312: [Bug]: SegmentedButton doesn't animate correctly on resize
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/design_system_flutter/blob/main/CONTRIBUTING.md) for this project.
- [x] I have searched the [issue tracker](https://github.com/SchweizerischeBundesbahnen/design_system_flutter/issues) for an issue that matches the one I want to file, without success.

### Bug type

Other

### Which release are you using?

3.0.0

### Flutter SDK version

3.27.4

### Additional settings

_No response_

### Expected

The SegmentedButton should correctly animate the selection when resizing.

### What happened?

The selection is not correctly during the animation and jumps in the end. This is noticable for the user also when the animation is quicker. Here is a video: (... sorry for the music didn't see that it records audio too 😄 )

https://github.com/user-attachments/assets/eca60d5f-a092-4c91-9625-fe086f56a8c3

### Steps to reproduce the issue

Add an SegmentedButton to a Widget that changes the width in an animation.

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by rawi-coding**
Also removed BoxShadow and fixed wrong color to match design spec.

https://github.com/user-attachments/assets/ebe54ba2-af73-485f-ba4c-066a2b2d8b12

====
closes #312

### CODE REVIEW

File: lib/src/segmented_button/sbb_segmented_button.dart [hunk 1]
```diff
@@ -214,37 +214,31 @@ class SegmentedButtonState extends State<SBBSegmentedButton> {
...
-                  borderRadius: _borderRadius,
-                  color: style?.selectedStyle?.backgroundColor,
-                  child: InkWell(
-                    borderRadius: _borderRadius,
-                    onTap: () {
-                      widget.selectedIndexChanged(widget.selectedStateIndex);
-                    },
-                  ),
-                ),
+      child: AnimatedAlign(
```
Comment (smallTrogdor) [inline lib/src/segmented_button/sbb_segmented_button.dart]: 🥇

File: lib/src/segmented_button/sbb_segmented_button.dart [hunk 2]
```diff
@@ -214,37 +214,31 @@ class SegmentedButtonState extends State<SBBSegmentedButton> {
...
+        alignment: Alignment(alignmentX, 0),
+        duration: kThemeAnimationDuration,
+        curve: Curves.easeInOut,
+        child: FractionallySizedBox(
```
Comment (smallTrogdor) [inline lib/src/segmented_button/sbb_segmented_button.dart]: 👑

File: lib/src/segmented_button/sbb_segmented_button.dart [hunk 3]
```diff
@@ -214,37 +214,31 @@ class SegmentedButtonState extends State<SBBSegmentedButton> {
   }
 
   Widget _buildIndicatorLayer() {
+    final buttonCount = widget.widgetBuilders.length;
+    final alignmentX = buttonCount <= 1 ? 0.0 : -1 + 2 * widget.selectedStateIndex / (buttonCount - 1);
```
Comment (smallTrogdor) [inline lib/src/segmented_button/sbb_segmented_button.dart]: just to make sure: is selectedStateIndex 0th based? If so, then if buttonCount == 2 and selectedStateIndex == 0, it would result in -1 for alignmentX? Is that then capped to 0?

Comment (smallTrogdor) [reply lib/src/segmented_button/sbb_segmented_button.dart]: thanks for the clarification 💯
